"""empty message

Revision ID: 2e6f97d750e5
Revises: 40588a70b5c6
Create Date: 2023-11-08 17:00:14.281983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6f97d750e5'
down_revision = '40588a70b5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_status', sa.Enum('draft', 'online', name='articlestatus'), server_default='online', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('article_status')

    # ### end Alembic commands ###
