"""empty message

Revision ID: 33db39cf43bc
Revises: 
Create Date: 2024-02-02 16:48:35.805668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33db39cf43bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=60), nullable=False),
    sa.Column('category_slug', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('classification',
    sa.Column('cla_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cla_name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('cla_id'),
    sa.UniqueConstraint('cla_name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('head_portrait', sa.String(length=200), nullable=True),
    sa.Column('is_VIP', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('add_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('article',
    sa.Column('article_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_name', sa.String(length=60), nullable=False),
    sa.Column('excerpt', sa.String(length=300), nullable=False),
    sa.Column('content', mysql.LONGTEXT(), nullable=False),
    sa.Column('article_status', sa.Enum('draft', 'online', name='articlestatus'), server_default='online', nullable=False),
    sa.Column('public_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('thumbnail', sa.String(length=200), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('articles_clas',
    sa.Column('cla_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.article_id'], ),
    sa.ForeignKeyConstraint(['cla_id'], ['classification.cla_id'], ),
    sa.PrimaryKeyConstraint('cla_id', 'article_id')
    )
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_date', sa.DateTime(), nullable=False),
    sa.Column('content', mysql.LONGTEXT(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.article_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('articles_clas')
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('classification')
    op.drop_table('category')
    # ### end Alembic commands ###
