"""empty message

Revision ID: 40588a70b5c6
Revises: 
Create Date: 2023-11-08 16:19:27.351704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40588a70b5c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=60), nullable=False),
    sa.Column('category_slug', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('classification',
    sa.Column('cla_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cla_name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('cla_id'),
    sa.UniqueConstraint('cla_name')
    )
    op.create_table('article',
    sa.Column('article_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_name', sa.String(length=60), nullable=False),
    sa.Column('excerpt', sa.String(length=300), nullable=False),
    sa.Column('content', mysql.LONGTEXT(), nullable=False),
    sa.Column('public_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('articles_clas',
    sa.Column('cla_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.article_id'], ),
    sa.ForeignKeyConstraint(['cla_id'], ['classification.cla_id'], ),
    sa.PrimaryKeyConstraint('cla_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles_clas')
    op.drop_table('article')
    op.drop_table('classification')
    op.drop_table('category')
    # ### end Alembic commands ###
